### ISSUE TITLE
No Member Named 'getNativeDisplay' in namespace 'glfw'.

### ISSUE THREAD

**Issue by sudhanvas** [OculusRiftInAction/OculusRiftInAction#86]
In HelloRift.cpp, I see the line:
ON_LINUX([&]{cfg.OGL.Disp = (Display*)glfw::getNativeDisplay(getWindow());});

This line, unfortunately, produces the following error: 
"no member named 'getNativeDisplay' in namespace 'glfw'"

How can I go about fixing this issue?

**Comment by sudhanvas** [comment]
When I use glfw::getNativeWindowHandle(GLFWwindow *) instead, it compiles fine. However, I still get the following runtime error:

Error: [Context] Unable to obtain x11 visual from context
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  174
  Current serial number in output stream:  174

Any suggestions on where the issue might be?

**Comment by jherico** [comment]
I just build I just build from a clean checkout of the repository on Ubuntu 14.  The getNativeDisplay function is present here:  https://github.com/OculusRiftInAction/OculusRiftInAction/blob/master/examples/cpp/common/glfw/GlfwUtils.cpp#L33  and is declared here:  https://github.com/OculusRiftInAction/OculusRiftInAction/blob/master/examples/cpp/common/glfw/GlfwApp.h  so I don't know why you'd be getting that error.  The getNativeWindowHandle returns an instance of the X11 Window type, while getNativeDisplay returns the X11 Display type.  You can't substitute one for the other, so that's why you're crashing if you try to pass in the window handle to the display value.

I would double-check your checked out git source and make sure it's up to date.

**Comment by sudhanvas** [comment]
I was able to fix the compilation error with the latest fix from the library. However, I still get the same runtime error, and this time with ovrHmd_ConfigureRendering at the end of initGl() in HelloRift app.

Error: [Context] Unable to obtain x11 visual from context
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  174
  Current serial number in output stream:  174

**Comment by jherico** [comment]
I know they've had issues in the past with the creation of a shared OpenGL context on Linux (they use a shared context to avoid changing state in the primary context).  

What kind of video card are you working with?   Are you able to build and run the examples that are included with the official SDK?

**Comment by sudhanvas** [comment]
I have the NVIDIA Corporation GK208M [GeForce GT 740M].
I am also able to build and run the Oculus World Demo Sample from the Oculus SDK.
